FROM node:11.9.0-alpine as builder
LABEL maintainer "Ibara Takanashi <ibara1454@gmail.com>"

# Set environment to development
ENV NODE_ENV development

# Add all files in current directory into container
COPY freja-backend workspace/
WORKDIR /workspace

RUN npm install \
    && npm run build

# ===================================

FROM node:11.9.0-alpine

ADD . / workspace/
COPY --from=builder /workspace /workspace
WORKDIR /workspace

ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000

RUN npm install
# Generate rootCA
RUN node_modules/anyproxy/bin/anyproxy-ca --generate

CMD ["npm", "run", "serve"]
