version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8001:8001" # Open 8001 for proxy port
      - "8002:8002" # Open 8002 for monitor page

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile-reverse-proxy
    ports:
      - 80:80       # Reverse proxying requests on port 80
