FROM node:11.9.0-alpine as builder
LABEL maintainer "Ibara Takanashi <ibara1454@gmail.com>"

# Add all files in current directory into container
COPY freja-frontend workspace/
WORKDIR /workspace

RUN echo "VUE_APP_API_ENDPOINT=''" > .env.production

RUN npm install\
    && npm run build

FROM halverneus/static-file-server
COPY --from=builder /workspace/dist/ /web
EXPOSE 8080
